export const repositories = [
  {
    iconUrl: require("../../assets/img/logo1.png"),
    name: "Anuluca/Anuluca.github.io",
    url: "Anuluca.github.io",
  },
  {
    iconUrl: require("../../assets/img/logo1.png"),
    name: "kaiiiz/hexo-theme-book",
    url: "https://github.com/kaiiiz/hexo-theme-book",
  },
  {
    iconUrl: require("../../assets/img/logo1.png"),
    name: "kb1000fx/kb1000fx.github.io",
    url: "kb1000fx.github.io",
  },
  {
    iconUrl: require("../../assets/img/logo2.png"),
    name: "Anuluca/hexo-theme-book-demo",
  },
];

export const mainContent = [
  {
    headerIconUrl: require("../../assets/img/header_other_small.jpg"),
    userName: "cutekibry",
    operation: "starred",
    objectName: "zcmimi/hosts-for-working-hard",
    postTime: "27 Aug",
    objectDiscrib: "防止颓废的hosts(颓废网址/ip黑名单)",
    language: "Python",
    stars: "4",
    updateTime: "Oct 1",
  },
  {
    headerIconUrl: require("../../assets/img/header_other_small.jpg"),
    userName: "cutekibry",
    operation: "starred",
    objectName: "zcmimi/hosts-for-working-hard",
    postTime: "27 Aug",
    objectDiscrib: "防止颓废的hosts(颓废网址/ip黑名单)",
    language: "Python",
    stars: "4",
    updateTime: "Oct 1",
  },
  {
    headerIconUrl: require("../../assets/img/header_other2_small.jpg"),
    userName: "诺天",
    operation: "created a repository",
    objectName: "zq1997/deepin-wine",
    postTime: "10 Aug",
    objectDiscrib: "Demo: https://removeif.github.io/removeif-demo hexo-theme",
    language: "Ruby",
    stars: "1.1k",
    updateTime: "Oct 11",
  },
  {
    headerIconUrl: require("../../assets/img/header_other_small.jpg"),
    userName: "cutekibry",
    operation: "starred",
    objectName: "zcmimi/hosts-for-working-hard",
    postTime: "27 Aug",
    objectDiscrib: "防止颓废的hosts(颓废网址/ip黑名单)",
    language: "Python",
    stars: "4",
    updateTime: "Oct 1",
  },
  {
    headerIconUrl: require("../../assets/img/header_other2_small.jpg"),
    userName: "诺天",
    operation: "created a repository",
    objectName: "zq1997/deepin-wine",
    postTime: "10 Aug",
    objectDiscrib: "【deepin源移植】Debian/Ubuntu上最快的QQ/微信安装方式",
    language: "Ruby",
    stars: "1.1k",
    updateTime: "Oct 11",
  },
  {
    headerIconUrl: require("../../assets/img/header_other_small.jpg"),
    userName: "cutekibry",
    operation: "starred",
    objectName: "zcmimi/hosts-for-working-hard",
    postTime: "27 Aug",
    objectDiscrib: "防止颓废的hosts(颓废网址/ip黑名单)",
    language: "Python",
    stars: "4",
    updateTime: "Oct 1",
  },
  {
    headerIconUrl: require("../../assets/img/header_other2_small.jpg"),
    userName: "诺天",
    operation: "created a repository",
    objectName: "zq1997/deepin-wine",
    postTime: "10 Aug",
    objectDiscrib: "【deepin源移植】Debian/Ubuntu上最快的QQ/微信安装方式",
    language: "Ruby",
    stars: "1.1k",
    updateTime: "Oct 11",
  },
];
